

function generateName() {
  var names = ["Fred", "Jim", "John", "Sid"];
  var randomIndex = Math.floor(Math.random() * names.length);
  var name = names[randomIndex];
  
  var nameElement = document.getElementById("resultName");
  nameElement.textContent = name;
  }
  
  function generatePhysicalTraits() {
    // Code for generating physical traits
    // Replace the code below with your own physical traits generation logic
    var traits = [
    "Tall",
    "Short",
    "Slender",
    "Athletic",
    "Muscular",
    "Curvy",
    "Chubby",
    "Stocky",
    "Petite",
    "Lean",
    "Broad-shouldered",
    "Lanky",
    "Well-built",
    "Toned",
    "Strong",
    "Thin",
    "Voluptuous",
    "Fit",
    "Average height",
    "Long-legged",
    "Short-legged",
    "Broad-chested",
    "Thin-waisted",
    "Narrow-shouldered",
    "Full-figured",
    "Heavyset",
    "Well-proportioned",
    "Sturdy",
    "Slouching",
    "Graceful",
    "Awkward",
    "Elegant",
    "Delicate",
    "Rugged",
    "Wiry",
    "Fragile",
    "Burly",
    "Curly-haired",
    "Bald",
    "Long-haired",
    "Short-haired",
    "Shaved head",
    "Wavy hair",
    "Straight hair",
    "Frizzy hair",
    "Messy hair",
    "Thin hair",
    "Thick hair",
    "Red hair",
    "Blonde hair",
    "Brunette hair",
    "Black hair",
    "Gray hair",
    "Salt-and-pepper hair",
    "Balding",
    "Dark-skinned",
    "Light-skinned",
    "Olive-skinned",
    "Tanned",
    "Pale",
    "Freckled",
    "Scarred",
    "Tattooed",
    "Pierced",
    "Wrinkled",
    "Smooth-skinned",
    "Acne-prone",
    "Rosy-cheeked",
    "Angular face",
    "Round face",
    "Square jaw",
    "High cheekbones",
    "Thin lips",
    "Full lips",
    "Crooked teeth",
    "Straight teeth",
    "Braces",
    "Dimples",
    "Cleft chin",
    "Almond-shaped eyes",
    "Round eyes",
    "Hooded eyes",
    "Small eyes",
    "Big eyes",
    "Wide-set eyes",
    "Narrow-set eyes",
    "Piercing gaze",
    "Bushy eyebrows",
    "Thin eyebrows",
    "Arched eyebrows",
    "Long eyelashes",
    "Sparse eyelashes",
    "Crooked nose",
    "Straight nose",
    "Button nose",
    "Large ears",
    "Small ears",
    "Prominent cheekbones",
    "Broad forehead",
    "Chiseled jawline"
    ];
    var rareTraits = [
      "Different-colored eyes (Heterochromia)",
      "Lack of pigmentation (Albinism)",
      "Fingers fused together by skin (Webbed fingers)",
      "Extra fingers or toes (Polydactyly)",
      "Loss of skin pigmentation in patches (Vitiligo)",
      "Missing or amputated limb",
      "Unusually short stature (Dwarfism)",
      "Excessive growth and height (Gigantism)",
      "Cleft in the upper lip",
      "Scars caused by burns",
      "Mark or discoloration on the face at birth (Facial birthmark)",
      "Abnormally small head size (Microcephaly)",
      "Abnormally large head size (Macrocephaly)",
      "Excessive hair growth (Hypertrichosis)",
      "Brittle bones (Osteogenesis imperfecta)",
      "Visible spots or floaters in the field of vision (Vitreous floaters)",
      "Extreme sensitivity to sunlight (Xeroderma pigmentosum)",
      "Joint hypermobility and stretchy skin (Ehlers-Danlos syndrome)",
      "Fingers or toes that are missing or fused together (Ectrodactyly)",
      "Uneven or asymmetrical facial features (Facial asymmetry)",
      "Fingers or toes that are fused together (Syndactyly)",
      "Two individuals physically connected at birth (Conjoined twins)",
      "Unusually thin and fragile bones (Osteogenesis imperfecta)",
      "Unusually flexible joints (Joint hypermobility)",
      "Lack of or reduced hair on the body (Alopecia)",
      "Unusually large birthmark or mole"
    ];
    var randomIndex = Math.floor(Math.random() * traits.length);
    var physicalTrait = traits[randomIndex];
    if (Math.random() <= 0.8) {
      randomIndex = Math.floor(Math.random() * traits.length);
      physicalTrait = traits[randomIndex] + ", " + [physicalTrait];  
    }
    if (Math.random() <= 0.25) {
      randomIndex = Math.floor(Math.random() * traits.length);
      physicalTrait = traits[randomIndex] + ", " + [physicalTrait];  
    } else if (Math.random() <= 0.25) {
      randomIndex = Math.floor(Math.random() * rareTraits.length);
      physicalTrait = [physicalTrait] + ", " + rareTraits[randomIndex];  
    }
    
    var physicalTraitsElement = document.getElementById("resultPhysicalTraits");
    physicalTraitsElement.textContent = physicalTrait;
  }
  
  function generatePersonalityTraits() {
    // Code for generating personality traits
    // Replace the code below with your own personality traits generation logic
    var traits = [
      "Ambitious",
      "Brave",
      "Compassionate",
      "Dependable",
      "Energetic",
      "Friendly",
      "Generous",
      "Honest",
      "Intelligent",
      "Loyal",
      "Optimistic",
      "Patient",
      "Resourceful",
      "Sincere",
      "Adventurous",
      "Calm",
      "Creative",
      "Determined",
      "Enthusiastic",
      "Gentle",
      "Humble",
      "Kind",
      "Modest",
      "Organized",
      "Passionate",
      "Rational",
      "Strong-willed",
      "Trustworthy",
      "Analytical",
      "Charismatic",
      "Diplomatic",
      "Empathetic",
      "Gracious",
      "Imaginative",
      "Logical",
      "Nurturing",
      "Perceptive",
      "Reliable",
      "Supportive",
      "Wise",
      "Assertive",
      "Caring",
      "Disciplined",
      "Empowered",
      "Honest",
      "Independent",
      "Motivated",
      "Open-minded",
      "Resilient",
      "Tenacious",
      "Adaptable",
      "Charming",
      "Diligent",
      "Forgiving",
      "Humorous",
      "Inspiring",
      "Meticulous",
      "Patient",
      "Reflective",
      "Thoughtful",
      "Assertive",
      "Confident",
      "Driven",
      "Graceful",
      "Imaginative",
      "Intuitive",
      "Nurturing",
      "Persistent",
      "Respectful",
      "Tactful",
      "Bold",
      "Cooperative",
      "Ethical",
      "Graceful",
      "Independent",
      "Joyful",
      "Modest",
      "Observant",
      "Proactive",
      "Responsible",
      "Self-disciplined",
      "Unselfish",
      "Brave",
      "Curious",
      "Enthusiastic",
      "Honest",
      "Intelligent",
      "Loyal",
      "Optimistic",
      "Patient",
      "Respectful",
      "Self-confident",
      "Trustworthy",
      "Versatile",
      "Warm-hearted",
      "Charitable",
      "Discerning",
      "Fearless",
      "Humble",
      "Self-motivated"
    ];
    var randomIndex = Math.floor(Math.random() * traits.length);
    var personalityTrait = traits[randomIndex];
    randomIndex = Math.floor(Math.random() * traits.length);
    personalityTrait = traits[randomIndex] + " and " + [personalityTrait];
    
    var personalityTraitsElement = document.getElementById("resultPersonalityTraits");
    personalityTraitsElement.textContent = personalityTrait;
  }

  function generateBeliefs() {
    var beliefs = [
      "Equality for all individuals, regardless of race, gender, or background",
      "The power of forgiveness and second chances",
      "Honesty and transparency in all relationships",
      "Personal responsibility and accountability for one's actions",
      "The pursuit of knowledge and continuous learning",
      "Compassion and empathy towards others",
      "Environmental conservation and sustainable living",
      "Freedom of expression and speech",
      "Respect for diversity and multiculturalism",
      "Justice and fairness in all matters",
      "The importance of family bonds and loyalty",
      "Non-violence and peaceful conflict resolution",
      "Self-discipline and self-control",
      "The power of love and kindness to transform lives",
      "The belief in the inherent worth and dignity of every individual",
      "Open-mindedness and willingness to consider different perspectives",
      "The pursuit of personal growth and self-improvement",
      "The value of hard work and perseverance",
      "The importance of community and collaboration",
      "The right to freedom and autonomy",
      "Integrity and ethical conduct in all endeavors",
      "The belief in the power of art and creativity",
      "The promotion of education and equal opportunities",
      "The preservation of cultural heritage and traditions",
      "The promotion of peace and global harmony",
      "The belief in the power of resilience and adaptability",
      "The value of trust and loyalty in relationships",
      "The pursuit of justice and human rights",
      "The importance of self-care and well-being",
      "The belief in the power of positive thinking",
      "The promotion of animal rights and welfare",
      "The value of humility and modesty",
      "The promotion of gender equality and feminism",
      "The belief in the importance of democratic principles",
      "The value of financial responsibility and frugality",
      "The promotion of social justice and equality",
      "The belief in the importance of civic engagement and activism",
      "The value of kindness and random acts of kindness",
      "The promotion of mental health awareness and support",
      "The belief in the power of imagination and creativity",
      "The value of forgiveness and letting go of grudges",
      "The promotion of sustainable and ethical consumption",
      "The belief in the power of teamwork and collaboration",
      "The value of personal integrity and moral courage",
      "The promotion of accessible healthcare for all",
      "The belief in the importance of community service and giving back",
      "The value of embracing diversity and inclusion",
      "The promotion of peacebuilding and conflict resolution",
      "The belief in the power of mindfulness and self-reflection",
      "The value of perseverance and resilience in the face of challenges",
      "The promotion of equality in education and access to knowledge",
      "The belief in the importance of social responsibility",
      "The value of optimism and positive thinking",
      "The promotion of responsible and sustainable business practices",
      "The belief in the power of forgiveness and reconciliation",
      "The value of active listening and effective communication",
      "The promotion of gender equity and equal opportunities",
      "The belief in the importance of emotional intelligence",
      "The value of volunteerism and community engagement",
      "The promotion of transparency and accountability in governance",
      "The belief in the power of education to transform lives",
      "The value of patience and understanding",
      "The promotion of ethical treatment of animals",
      "The belief in the importance of personal autonomy and freedom of choice",
      "The value of embracing change and adaptability",
      "The promotion of fair trade and ethical consumerism",
      "The belief in the power of resilience and inner strength",
      "The value of empathy and active listening",
      "The promotion of cultural diversity and preservation",
      "The belief in the importance of equality in healthcare",
      "The value of self-expression and creativity",
      "The promotion of environmental sustainability and conservation",
      "The belief in the power of collaboration and cooperation",
      "The value of personal authenticity and self-acceptance",
      "The promotion of equal rights and opportunities for all",
      "The belief in the importance of work-life balance",
      "The value of gratitude and appreciation",
      "The promotion of responsible and ethical use of technology",
      "The belief in the power of community support and solidarity",
      "The value of personal independence and self-reliance",
      "The promotion of fair and just economic systems",
      "The belief in the importance of continuous personal growth",
      "The value of mindfulness and living in the present moment",
      "The promotion of gender inclusivity and LGBTQ+ rights",
      "The belief in the power of positive relationships and connections",
      "The value of curiosity and lifelong learning",
      "The promotion of affordable housing and alleviation of homelessness",
      "The belief in the importance of social cohesion and harmony",
      "The value of self-care and mental well-being",
      "The promotion of ethical and sustainable fashion",
      "The belief in the power of self-belief and confidence",
      "The value of respecting and protecting indigenous rights",
      "The promotion of responsible and sustainable tourism",
      "The belief in the importance of equality in the workplace",
      "The value of embracing failure as an opportunity for growth",
      "The promotion of accessible and inclusive transportation",
      "The belief in the power of optimism and positive mindset",
      "The value of community resilience and disaster preparedness",
      "The promotion of universal access to clean water and sanitation",
      "The belief in the importance of love and compassion as guiding principles"
    ];
    var randomIndex = Math.floor(Math.random() * beliefs.length);
    var belief = beliefs[randomIndex];
    randomIndex = Math.floor(Math.random() * beliefs.length);
    belief = beliefs[randomIndex] + " and " + [belief];
    
    var beliefElement = document.getElementById("resultBeliefs");
    beliefElement.textContent = belief;
  }

  function generateFlaws() {
    var flaws = [
      "Impulsiveness",
      "Procrastination",
      "Jealousy",
      "Arrogance",
      "Insecurity",
      "Stubbornness",
      "Selfishness",
      "Laziness",
      "Indecisiveness",
      "Overthinking",
      "Pessimism",
      "Indulgence in vices (e.g., smoking, drinking)",
      "Perfectionism",
      "Hot-temperedness",
      "Disorganization",
      "Manipulative behavior",
      "Self-doubt",
      "Lack of empathy",
      "Judgmental attitude",
      "Gullibility",
      "Workaholism",
      "Defensiveness",
      "Impatience",
      "Tendency to be overly critical",
      "Carelessness",
      "Tendency to jump to conclusions",
      "Overly competitive nature",
      "Inability to trust others",
      "People-pleasing behavior",
      "Lack of assertiveness",
      "Disloyalty",
      "Inability to forgive and forget",
      "Tendency to avoid confrontation",
      "Neglect of personal relationships",
      "Excessive worrying",
      "Inability to take risks",
      "Tendency to be overly self-critical",
      "Proclivity for lying or deception",
      "Manipulative behavior",
      "Fear of commitment",
      "Tendency to hold grudges",
      "Impersonal or distant demeanor",
      "Tendency to be easily distracted",
      "Excessive need for control",
      "Tendency to be overly sensitive",
      "Lack of self-discipline",
      "Disregard for rules or authority",
      "Tendency to be easily influenced",
      "Self-centeredness",
      "Inability to handle criticism",
      "Excessive pride",
      "Tendency to be overly defensive",
      "Lack of self-awareness",
      "Inability to handle stress",
      "Proclivity for gossiping",
      "Tendency to be overly competitive",
      "Envy or resentment towards others",
      "Tendency to blame others",
      "Addiction to technology or social media",
      "Tendency to avoid responsibility",
      "Impersonal or aloof behavior",
      "Tendency to overeat or indulge in comfort food",
      "Excessive need for validation or approval",
      "Lack of commitment or follow-through",
      "Tendency to be manipulative for personal gain",
      "Tendency to be overly passive or submissive",
      "Disregard for others' boundaries",
      "Tendency to be overly dramatic",
      "Inability to manage time effectively",
      "Tendency to be overly defensive or argumentative",
      "Lack of attention to detail",
      "Excessive need for control in relationships",
      "Tendency to be easily swayed by others' opinions",
      "Lack of accountability",
      "Excessive materialism or consumerism",
      "Tendency to be overly pessimistic or cynical",
      "Excessive need for validation from others",
      "Tendency to be overly secretive or guarded",
      "Disregard for personal health or well-being",
      "Tendency to be overly possessive or clingy in relationships",
      "Lack of self-motivation",
      "Tendency to avoid confrontation at all costs",
      "Excessive self-criticism or self-blame",
      "Tendency to be overly judgmental of others",
      "Lack of self-control in spending or impulse buying",
      "Tendency to be overly controlling in personal relationships",
      "Tendency to be overly dependent on others",
      "Tendency to be overly critical of others' work or ideas",
      "Lack of flexibility or adaptability",
      "Tendency to be overly pessimistic or negative",
      "Inability to accept feedback or constructive criticism",
      "Excessive need for attention or validation",
      "Tendency to be overly defensive or reactive in conflicts",
      "Lack of empathy or understanding towards others' feelings",
      "Tendency to be easily swayed by peer pressure",
      "Excessive need for approval or validation from authority figures",
      "Tendency to avoid taking risks or stepping out of comfort zones",
      "Inability to handle change or adapt to new situations",
      "Tendency to be overly possessive or jealous in relationships",
      "Lack of self-confidence or low self-esteem"
    ];
    var randomIndex = Math.floor(Math.random() * flaws.length);
    var flaw = flaws[randomIndex];
    if (Math.random() <= 0.5) {
      randomIndex = Math.floor(Math.random() * flaws.length);
      flaw = flaws[randomIndex] + ", " + [flaw];  
    }
    
    var flawsElement = document.getElementById("resultFlaws");
    flawsElement.textContent = flaw;
  }
  
  function generateBackground() {
    // Code for generating background
    // Replace the code below with your own background generation logic
    var backgrounds = ["Noble", "Outlaw", "Merchant", "Scholar"];
    var randomIndex = Math.floor(Math.random() * backgrounds.length);
    var background = backgrounds[randomIndex];
    
    var backgroundElement = document.getElementById("resultBackground");
    backgroundElement.textContent = background;
  }

  